synchro: update

diff --git a/usr/bin/synchro b/usr/bin/synchro
--- a/usr/bin/synchro
+++ b/usr/bin/synchro
@@ -5,29 +5,29 @@
 yellow() { tput setaf 3; echo "$@"; tput sgr0; }
 
 bold() { tput bold; echo "$@"; tput sgr0; }
- die() { red "$@" >&2; exit 1; }
+fail() { red "$@" >&2; exit 1; }
 
 conf_file=/etc/synchro.conf
 source_dirs="/etc /home /root"
-exclude="*"
+exclude="**"
 backup_dir=/path/to/backup/dir
 
 if ! source "$conf_file" 2>/dev/null; then
     echo -n "Config file is missing: "; red "$conf_file"
-    die
+    fail
 fi
 
-check_backup_dir_or_die()
+check_backup_dir_or_fail()
 {
     if [[ ! -d "$backup_dir" ]]; then
         echo -n "Backup dir does not exist: "; red "$backup_dir"
-        die
+        fail
     fi
 }
 
 backup()
 {
-    check_backup_dir_or_die
+    check_backup_dir_or_fail
 
     mkdir -p "${backup_dir}/backup.0"
     rsync -avHAX --delete --exclude-from=- ${source_dirs[@]} "${backup_dir}/backup.0/" <<< "$exclude"
@@ -35,7 +35,7 @@ backup()
 
 display()
 {
-    check_backup_dir_or_die
+    check_backup_dir_or_fail
 
     echo -n "Backups in: "; bold "$backup_dir"
     cd "$backup_dir"
@@ -46,38 +46,38 @@ display()
 
 remove()
 {
-    check_backup_dir_or_die
+    check_backup_dir_or_fail
 
     cd "$backup_dir"
     local backup=$(ls -1dv backup.[0-9] backup.[0-9][0-9] 2>/dev/null | tail  -n1)
 
     red -n "[delete]"; echo " $backup"
-    rm -rI "$backup" || die "FAILED"
+    rm -rI "$backup" || fail "FAILED"
 }
 
 rotate()
 {
-    check_backup_dir_or_die
+    check_backup_dir_or_fail
 
     cd "$backup_dir"
     local backups=$(ls -1dvr backup.[0-9] backup.[0-9][0-9] 2>/dev/null)
 
     for backup in $backups; do
         local n=${backup#backup.}
-        local new_backup="backup.$((n+1))" 
+        local new_backup="backup.$((n+1))"
 
         green -n "[rename]"; echo " $backup -> $new_backup"
-        mv -T "$backup" "$new_backup" || die "FAILED"
+        mv -T "$backup" "$new_backup" || fail "FAILED"
     done
 
     yellow -n "[mirror]"; echo " $new_backup -> backup.0"
-    cp -al "$new_backup" backup.0 || die "FAILED"
+    cp -al "$new_backup" backup.0 || fail "FAILED"
     touch backup.0
 }
 
 rotate_back()
 {
-    check_backup_dir_or_die
+    check_backup_dir_or_fail
 
     cd "$backup_dir"
     local backups=$(ls -1dv backup.[0-9] backup.[0-9][0-9] 2>/dev/null)
@@ -88,10 +88,10 @@ rotate_back()
 
         if ((n == 0)); then
             red -n "[delete]"; echo " $backup"
-            rm -rI "$backup" || die "FAILED"
+            rm -rI "$backup" || fail "FAILED"
         else
             green -n "[rename]"; echo " $backup -> $new_backup"
-            mv -T "$backup" "$new_backup" || die "FAILED"
+            mv -T "$backup" "$new_backup" || fail "FAILED"
         fi
     done
 }
@@ -110,5 +110,5 @@ case "$1" in
     remove) remove "$@";;
     rotate) rotate;;
     rotate_back) rotate_back;;
-    *) usage; die "Invalid action";;
+    *) usage; fail "Invalid action";;
 esac
